name: JoinLeaveAction
main: my.smk.plugin.jla.Main
version: 0.1.5
author: smk7758
website(my): http://smk7758.web.fc2.com/
website(plugin): none
permissions:
   JoinLeaveAction.*:
       description: Gives the user access to all command.
       children:
           JoinLeaveAction.cmd: true
           JoinLeaveAction.cmd.setspawn: true
           JoinLeaveAction.cmd.spawn.me: true
           JoinLeaveAction.cmd.spawn.other: true
       description: Allows the JoinLeaveAction Plugin use.
       default: false
   JoinLeaveAction.cmd:
       description: Allows the JoinLeaveAction's commands.
       default: false
       children:
           JoinLeaveAction.cmd.setspawn: true
           JoinLeaveAction.cmd.spawn.me: true
           JoinLeaveAction.cmd.spawn.other: true
   JoinLeaveAction.cmd.setspawn:
       description: Allows the /setspawn command.
       default: false
   JoinLeaveAction.cmd.spawn:
       description: Allows the /spawn [player] command.
       default: false
       children:
           JoinLeaveAction.cmd.spawn.me: true
           JoinLeaveAction.cmd.spawn.other: true
   JoinLeaveAction.cmd.spawn.me:
       description: Allows the /spawn command.
       default: false
   JoinLeaveAction.cmd.spawn.other:
       description: Allows the /spawn [player] command.
       default: false
commands:
   JoinLeaveAction:
    description: JoinLeaveAction.
    permission-message: You don't have <permission>
    aliases: jla
   setspawn:
    description: You can setspawn.
    permission-message: You don't have <permission>
   spawn:
    description: You go to spawn.
    permission-message: You don't have <permission>
